coming_url = "https://docs.google.com/forms/d/e/1FAIpQLSeN9IWKbI_QzYeT6eMoOTzYYtn2Mgn6-rozbrFcL7CoHbUHdA"
expense_url = "https://docs.google.com/forms/d/e/1FAIpQLScbGuUZ_xn4zXHzFD2IfspZzIe5--jzq_nqtLDwSQALpRbTsQ"
delete_url = "https://docs.google.com/forms/d/e/1FAIpQLSdHSxG1g7jg-OIaURRKDynpwJo9gHCIlKYG51sJRNHjni0W2Q"
credit_url = "https://docs.google.com/forms/d/e/1FAIpQLSfVLSuhosys6-_sdFnGjiAo_Bd1kn6pwtKR8IU469tgIRpJ1Q"
saving_url = "https://docs.google.com/forms/d/e/1FAIpQLSf2-CivdABiM7mepl3qyeBy0OcvHH08mB91VgrF4Lp_iDYMgg"
