"""initial_migration

Revision ID: 407468f1d1ee
Revises: 
Create Date: 2026-03-16 12:50:26.639786

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '407468f1d1ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bot_token', sa.Text(), nullable=False),
    sa.Column('spreadsheet_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_project_key'), 'projects', ['project_key'], unique=True)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Enum('EXPENSE', 'COMING', 'BORROWED_EXPENSE', 'REPAYMENT', name='operation_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_SYNC', 'SYNCED', 'SYNC_FAILED', 'DELETED', name='operation_status'), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('chapter_code', sa.String(length=64), nullable=True),
    sa.Column('category_code', sa.String(length=64), nullable=True),
    sa.Column('subcategory_code', sa.String(length=64), nullable=True),
    sa.Column('coming_code', sa.String(length=64), nullable=True),
    sa.Column('creditor', sa.String(length=255), nullable=True),
    sa.Column('coefficient', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_operations_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations'))
    )
    op.create_index(op.f('ix_operations_project_id'), 'operations', ['project_id'], unique=False)
    op.create_table('sync_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('APPLY_OPERATION', 'DELETE_OPERATION', name='sync_task_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='sync_status'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_sync_tasks_operation_id_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sync_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_tasks'))
    )
    op.create_index(op.f('ix_sync_tasks_operation_id'), 'sync_tasks', ['operation_id'], unique=False)
    op.create_index(op.f('ix_sync_tasks_project_id'), 'sync_tasks', ['project_id'], unique=False)
    op.create_table('sync_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='sync_attempt_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_task_id'], ['sync_tasks.id'], name=op.f('fk_sync_attempts_sync_task_id_sync_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_attempts'))
    )
    op.create_index(op.f('ix_sync_attempts_sync_task_id'), 'sync_attempts', ['sync_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_attempts_sync_task_id'), table_name='sync_attempts')
    op.drop_table('sync_attempts')
    op.drop_index(op.f('ix_sync_tasks_project_id'), table_name='sync_tasks')
    op.drop_index(op.f('ix_sync_tasks_operation_id'), table_name='sync_tasks')
    op.drop_table('sync_tasks')
    op.drop_index(op.f('ix_operations_project_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_projects_project_key'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
